# Generated by Django 5.0.3 on 2024-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.PositiveIntegerField(verbose_name='Response Code')),
                ('method', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('patch', 'PATCH'), ('delete', 'DELETE')], max_length=10, verbose_name='API Method')),
                ('url', models.CharField(max_length=400, verbose_name='URL')),
                ('request_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Request Received Time')),
                ('response_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Response Received Time')),
                ('utc_time_logged', models.DateTimeField(auto_now_add=True, verbose_name='UTC Time Logged')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'db_table': 'request_logs',
                'indexes': [models.Index(fields=['utc_time_logged', 'url'], name='request_log_utc_tim_ac8ceb_idx')],
            },
        ),
    ]
